### ISSUE TITLE
Switch to the PayPal transaction flow where 100% of donors get routed back to the thank you page to improve analytics

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#10]

**Comment by adamlofting** [comment]
As step one for this ticket, let's check which version of the PayPal checkout flow we used during EOY.

**Comment by ScottDowne** [comment]
Not finding anything useful on express checkout. I'm looking for an example that's ideally not in php.

Either of you have anything? I'm super frustrated with this issue.

**Comment by ScottDowne** [comment]
This was helpful and quite complete, and not easy to find: https://developer.paypal.com/webapps/developer/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/

**Comment by ScottDowne** [comment]
I have it working, patch incoming.

One downfall is we lose the obvious reassurance that this is a donation and not a sale. I have not figured out how to fix this. I also wonder what kind of receipt this is going to give out.

Express Checkout labels it as a purchase which could be confusing for someone.

Wikipedia using the classic checkout (The one we're using on production). We should ask them while in SF how they handle metrics for paypal. Really this isn't an issue about a silly redirect, it's about metrics.

**Comment by ScottDowne** [comment]
Here is the basic idea with express checkout: https://github.com/mozilla/donate.mozilla.org/pull/87

I also still think there is value with IPN (instant payment notifications), because it stays as a "donation" and is otherwise more flexible because it separates the problem and doesn't rely on the type of checkout. It'll be roughly the same amount of code and complexity.

https://github.com/mozilla/donate.mozilla.org/pull/88

Looks super simple right now, but still needs some work. Once the work is done is when it'll be about the same in complexity, because it requires some sort of server side google analytics lib or post. However, paypal can be told to pass the google analytics info along in the ipn message, so this should be easy.

**Comment by adamlofting** [comment]
> Really this isn't an issue about a silly redirect, it's about metrics.

While I've personally been pushing this from a metrics / increased speed of optimization tests point of view, the redirect itself is important. The thank you page is where we get people to opt-in to email comms, and this affects whether or not we can ask them to donate again in the future.

Increasing email opt-ins for donors by 30% or so is a big win for building long term fundraising relationships (and delivers real :dollar: value). :+1: 

> Wikipedia using the classic checkout (The one we're using on production). We should ask them while in SF how they handle metrics for paypal. 

That's an excellent idea. 

My concern with the IPN version using server side GA is how we can link up the GA session data so that GA knows which transaction relates to which original visit (usually managed via the browser cookie). Knowing whether a donation came from snippet or email is the most valuable part of that data. This might be fine, but I've not seen how it's done before.

**Comment by adamlofting** [comment]
> One downfall is we lose the obvious reassurance that this is a donation and not a sale. I have not figured out how to fix this. I also wonder what kind of receipt this is going to give out.

Without looking into the details I suggest we try to name the product "Donation to Mozilla Foundation" or something similar.

**Comment by ScottDowne** [comment]
Updated https://github.com/mozilla/donate.mozilla.org/pull/87/files

**Comment by ScottDowne** [comment]
Issue to flag.

I was doing all my testing with a sandbox account setup as canadian. When I plugged in better test account info for the default envs I decided to setup a US sandbox account.

Turns out they are rolling out UI updates to express checkout, and US gets it before Canadian. Canadian is going to get it later, so it'll be an issue either way.

Now using their new UI there is no way to describe the purchase, and it also displays some text "You'll be able to review your order before you complete your purchase." which isn't going to be true for us... and if we add that bit, it becomes another page and another click, which isn't awesome.

Thoughts? Page now looks like this:

![paypalisnotmypal](https://cloud.githubusercontent.com/assets/197334/8883642/5c98d7ba-321e-11e5-88bf-96608822ebd5.png)

If this is fine as is we're good to go. Personally I'm pissed they cannot just do a simple redirect.

**Comment by adamlofting** [comment]
> Now using their new UI there is no way to describe the purchase, and it also displays some text "You'll be able to review your order before you complete your purchase." which isn't going to be true for us... and if we add that bit, it becomes another page and another click, which isn't awesome.

I'm not worried about this. We set the donation tone earlier in the UX when we're asking for support. By the time the user is on this page, it's just 'doing the paperwork'.

I'm optimistic that their UI updates come from some heavy A/B testing.

**Comment by ScottDowne** [comment]
I'm not super optimistic. I'm glad you are still ok with it, that makes me feel a bit better about it.

I'm mostly now worried about the "You'll be able to review your order before you complete your purchase." and that I cannot find any docs for removing it. The UI changes are fine, it's just that they snuck up on me. The old UI I could remove that message.

**Comment by ScottDowne** [comment]
I filed it with them, not sure if this is sharable: https://www.paypal-techsupport.com/app/account/questions/detail/i_id/1144765

The custom style only changes colours for background header border, stuff like that. You cannot do straight up CSS.

**Comment by adamlofting** [comment]
I'm just noting our conversation from the stand-up for anyone following asynchronously. I had thought the concern was about donation vs payment language, but it's actually about a change the steps to the flow.

Previously we were able to configure the PayPal checkout flow not to require an extra confirmation page on our site. So the paypal page just said 'pay now', and sent the user straight to our thank you page.

The new PayPal UX doesn't appear to be backwards compatible with that configuration option. This may be a bug, or may be a change in how it works.

For now, we're progressing assuming it's a bug until we hear back from PayPal.

If this isn't a bug, we need to adjust our plans. Possible options are:

1. Add a confirmation page on our site before transaction is complete (feels like it could impact on conversion, but could be tested)
2. Investigate PayPal rest API as noted by jbuck - not clear how this works yet
3. Some other option we haven't looked into yet

**Comment by ScottDowne** [comment]
They responded!

Looks like it worked for them, so that tells us this is solvable, we just need to figure out what we're doing differently than them in their test.

The only difference I see is they had a `/checkout/review ` at the end of their redirect. So I'll try that.

It still feels like a bug on their end. If my link is wrong, it shouldn't display half a thing. very confusing.

However, tomorrow we'll find out if we have a working work around or not.

**Comment by ScottDowne** [comment]
https://github.com/mozilla/donate.mozilla.org/pull/87/files

Yes!

**Comment by adamlofting** [comment]
This ticket just made my day! :hatched_chick:
