### ISSUE TITLE
GA campaign consistency: EOY15 vs. EOYFR2015 in snippet URLs

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1001]
@adamlofting Jean mentioned today they have been using a campaign code "EOY15" for snippet URLs. E.g.:

https://donate.mozilla.org/en-US/?currency=inr&amp;utm_source=desktop-snippet&amp;utm_medium=snippet&amp;utm_term=5494&amp;utm_content=5494C&amp;utm_campaign=EOY15

Our correct campaign is "EOYFR2015" per the sheet here: https://docs.google.com/spreadsheets/d/1GIhOB5ERW9FvvNazBaLKsEX6ZFga3GYWDFd7b4zrCPs/edit#gid=0

1. Should she correct the parameter to conform to the campaign we've established?
2. Does this impact analytics in any way?

**Comment by adamlofting** [comment]
I don't think we need to worry about this for 2015. 

That 'campaign' level flag will be more useful in the future if we have multiple (different) campaigns running at the same time. It's a good practice to get into, but not an issue for us right now.

Because everything right now is EOY, we're really just looking at the source/medium level of segmentation.
