### ISSUE TITLE
en-US directory tiles URL isn't correct I think 

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#1012]
Right now the URL is: https://donate.mozilla.org/?&amount=10&ref=EOYFR2015&utm_campaign=EOYFR2015&utm_source=directory-tiles&utm_medium=tiles&utm_content=dapper_v1 

Is the URL meant to have the en-US locale or not?

**Comment by adamlofting** [comment]
This might be accidental, but it works out pretty well at the moment if this tile is catching all en-* traffic.

In my case if I open that URL I get forwarded to the en-GB variant with the parameters intact. The same should apply in en-CA.

(We can't use the same rule on the snippet because the amount and currency are already applied on the snippet, but for tiles this is good)

**Comment by jbuck** [comment]
Okay, I just wanted to make sure this was the intended URL. Thanks @adamlofting!
