### ISSUE TITLE
Inconsistent currency symbols displayed for some currencies

### ISSUE THREAD

**Issue by flodolo** [mozilla/donate.mozilla.org#1018]
Compare the currency symbols displayed in
https://donate.mozilla.org/ru/?currency=rub

With
https://donate.mozilla.org/en-US/?currency=rub

The second is the same you get by visiting the locale agnostic URL https://donate.mozilla.org/ and selecting RUB from the dropdown.

**Comment by flodolo** [comment]
It actually happens for most locales with a currency symbol (AUD, CAD, CNY, CZK, DKK, then I stopped trying).

**Comment by alicoding** [comment]
This is actually not design by us, but JavaScript standard for `Intl` using NumberFormat method.
```
var options = { style: 'currency', currency: 'RUB' };
var numberFormat = new Intl.NumberFormat('ru-RU', options);
console.log(numberFormat.format(50.20));
// 50,20 руб.
```
```
var options = { style: 'currency', currency: 'RUB' };
var numberFormat = new Intl.NumberFormat('USD', options);
console.log(numberFormat.format(50.20));
// RUB50.20
```

**Comment by alicoding** [comment]
The thing here is that if you use your locale for your currency then you will see the currency symbol, but if you try to look at it using different locale then you will see a letter currency instead of the symbol. I know it doesn't feel right.

**Comment by flodolo** [comment]
Thanks for the explanation. It's quite an edge case, so it's probably a WONTFIX if fixing it requires too much code (i.e. I wish Intl would be able to spit out just the currency).

**Comment by alicoding** [comment]
@flodolo that's actually what we wanted to do at first, but doesn't seem to be an easy, non-hacky way to do so :(

**Comment by jbuck** [comment]
I had a look at [the spec](http://www.ecma-international.org/ecma-402/1.0/#sec-11.3.2) because this was an interesting case to me, and the intended behaviour is basically "look up currency symbol in locale dictionary, if it doesn't exist then use the currency code itself" (step 6c). If you look at the Intl data for en-US you can see that it doesn't have the symbol for RUB: https://github.com/andyearnshaw/Intl.js/blob/292c317ab5c0cc89920f297620000e0b635ed2df/locale-data/json/en-US.json#L2176-L2197
