### ISSUE TITLE
Write January Thank You email to donors

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1026]
Write copy for the January email. This will sent in English, with a possible German version, to anyone that donated to the end-of year campaign. Last year's copy is here: https://public.etherpad-mozilla.org/p/text_from_EOY_2014_thankyou_email

Design ticket is #810 

** This should actually be written prior to Dec 18 so we have time adjust it in the template if necessary **

**Comment by valianttry** [comment]
@KevZawacki is going to take an initial stab at a draft.

**Comment by KevZawacki** [comment]
@valianttry @edrushka @HPaulJohnson 

First draft ready for review, [here](https://docs.google.com/document/d/1Q17cwH3DKoEDHsLvxCNUhIyz0P4xKL_JyEwppC6I0oM/edit#).

**Comment by edrushka** [comment]
cc @stephaniemcv

**Comment by edrushka** [comment]
This is great @KevZawacki! R+

**Comment by valianttry** [comment]
This still has some review and approvals to complete (e.g. I haven't seen it yet) so re-opening.

**Comment by valianttry** [comment]
@KevZawacki the email is solid! I made a few edits, and i also added a special paragraph for the segment of donors who we emailed even after they donated  because of a technical error. @stephaniemcv I think this is ready to send to Mark for review and approval. Make sure to paste it directly into an email to him vs. sending a link to the doc. Give Mark a specific deadline for getting back to you with approval.
