### ISSUE TITLE
Are we defaulting to monthly anywhere? I'm seeing higher than usual accidental monthly gifts

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1027]
I've seen a few strange emails today all saying they "made a monthly donation by mistake". Have we rolled out a default-monthly test? Here's the Transaction ID: ch_17DERnG8Mmx3htnx6BXjJucW

Example email:
![donation_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/11552732/bbe00100-993c-11e5-9ac0-3ba295428383.png)

@ScottDowne @jbuck

**Comment by ScottDowne** [comment]
Nothing intentional. Could be a bug? Pretty bad one too if so. I cannot reproduce anything like this though.

**Comment by valianttry** [comment]
Is it possible we have an accidental ?=monthly parameter somewhere?

**Comment by adamlofting** [comment]
We've not set any tests up for default to monthly (though there is one on the plan). 

We're getting traffic arriving on the ?frequency=monthly parameter, but that is also what happens if you check the monthly checkbox on the snippet. So it's hard to pinpoint any accidental cases via GA.

If this keeps happening we might want to review the UI to see if we can make the monthly / one-off options clearer in some way. 

We might just be seeing more of this because we've made the monthly option visible to more people (ie on the snippet).

I saw this text on Wikimedia donate form, we might want something similar in our footer:

> "*If you make a recurring donation, you will be debited by the Wikimedia Foundation until you notify us to stop. We'll send you an email receipt for each payment, which will include a link to easy cancellation instructions."

**Comment by ScottDowne** [comment]
I see no evidence it's a bug. Let's keep our eyes open, because if it's a bug, we'll see more.

**Comment by ScottDowne** [comment]
Any frequency param that's not monthly, is single. So even a typo would mean it ends up a single and not monthly. So we have to pretty explicitly set it as monthly.

I'll take a look at the various mozilla.org takeovers. Already checked snippets, they are fine.

**Comment by ScottDowne** [comment]
Nothing in the takeover too, seems to all work after me trying weird combinations of buttons.

**Comment by valianttry** [comment]
OK, i assume it's just people ticking a box without reading... it's not a large number of people. It does create a little extra donor management, as people are requesting help.

**Comment by ScottDowne** [comment]
Oddly enough, I think the "the really helps us" arrow test is going to reduce any accidental clicks to monthly.
