### ISSUE TITLE
Build and test a short survey for donors

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#1106]
I figured we should create a bug for implementation.

The final copy is linked here:
https://github.com/mozilla/donate.mozilla.org/issues/746

@TylerDowner set up a SurveyGizmo account. @adamlofting suggested we create a simple popup survey. 

@adamlofting feel free to edit labels or Milestone; etc!

**Comment by adamlofting** [comment]
I'll work on this asap.

**Comment by adamlofting** [comment]
After some investigation today, SurveyGizmo's pop-up is not something we'd want to use.

Their pop-up doesn't display the survey, just a (badly styled) message that links out to the full survey page.

Screenshot:
<img width="834" alt="screenshot 2015-12-16 13 09 03" src="https://cloud.githubusercontent.com/assets/1901816/11842978/e57be930-a3fe-11e5-838d-0b44516f8cae.png">

So, in order to improve this, I've added a new page to the donate repo which includes the survey within an iframe, and looks like this:

<img width="758" alt="screenshot 2015-12-16 14 04 35" src="https://cloud.githubusercontent.com/assets/1901816/11843028/20418cd2-a3ff-11e5-81a3-a41bc5149518.png">

I've just opened a pull request for this new page so we can get it onto staging and test it more thoroughly.

**Comment by adamlofting** [comment]
@valianttry what are you thoughts on where we should offer the survey?

I think we have three options, which we can use on either of our thank you pages:

1. Redirect X% of people straight to the survey
2. Promote the survey with a pop-up messge to X% of people
3. Display a message / link within the content of the thank you page for X% of people

**Current thank you pages for reference:**

Initial Thank You page with email opt-in ask:
<img width="847" alt="screenshot 2015-12-16 13 14 12" src="https://cloud.githubusercontent.com/assets/1901816/11843104/9730bfac-a3ff-11e5-8bdb-b4daaaefda2e.png">

Second thank you page with social share ask:
<img width="964" alt="screenshot 2015-12-16 13 14 03" src="https://cloud.githubusercontent.com/assets/1901816/11843108/9dd3cdf4-a3ff-11e5-81f1-c6ee32be73fc.png">

**Comment by adamlofting** [comment]
Here's the link to preview the survey on staging: https://donate.mofostaging.net/en-US/survey/

(this isn't in the donor flow right now so no one is currently seeing this)

**Comment by adamlofting** [comment]
Discussed this with Andrea. Our intention was to send a % of donors straight to the survey on the thank you page, but then realised this would cause issues with conversion tracking for GA and Optimizely which is fired on this page.

As a second best option, I have redirected 50% of en-US traffic from the `/share/` page (after email opt-in) to the survey. 

Over the course of the weekend, this will put the survey in front of ~1000 people.

**Comment by valianttry** [comment]
@adamlofting seems like traffic is really low to the survey -- is it working OK?

**Comment by adamlofting** [comment]
:crying_cat_face:

This is the weird quirk with how React and Optimizely work together. 

It was only applying the test to people who landed directly on (or refreshed) the share page. Most people don't do this, and our site silently moves them to the share page without Optimizely knowing. This is a quirk of React, but good for the user experience generally. It just makes the test setup more tricky.

I'll update this morning.

**Comment by adamlofting** [comment]
This is now working for traffic from en-us, en-gb and en-ca - redirecting 50% of traffic from the Share page.

**Comment by adamlofting** [comment]
This was done. I'll write up the results asap.
