### ISSUE TITLE
Update standard Mozilla email template

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1108]
Our initial work on the January Thank You Email #810 led us to the decision that we should update our standard/general email template. This will be used for a variety of emails throughout 2016 including:
- January thank you email
- Advocacy emails
- Fundraising emails

This template should be fairly simple. It should be Mozilla branded. It should be able to feature a call out graphic, or not, as necessary. 

Additional features (P2) could include the ability to highlight a CTA, the ability to highlight a text quote, and the ability to incorporate photos.

cc @cassiemc @valianttry @stephaniemcv @HPaulJohnson @KevZawacki @lovegushwa

**Comment by lovegushwa** [comment]
@stephaniemcv check out the new email template hot off the press for Teach via @kristinashu 
The big question's are:
- can we / should we adapt this template since it's the closest thing we have to a "house style"
- what features should we add / kill to make this as flexible as possible for EOY and advocacy.
(maybe we can do a bit of on the fly wire framing if necessary.)

We can also steal ideas from: http://reallygoodemails.com/


![teach-email-05 2x](https://cloud.githubusercontent.com/assets/12228435/11881716/4c9c0fb4-a4bd-11e5-8ea8-1b8bb4a0059b.jpg)

**Comment by stephaniemcv** [comment]
I think this template is great starting point of a "house style". I'm documenting some points here from our meeting with Ben N. Feel free to add anything I missed!

*Max width of email = 600px (best for scaling down to mobile)
*Hero images in templates scale and render more easily than call out images in sidebars
*Single column design is better for responsive code to render on mobile, multiple columns require more production time and code testing 
*Background images do not have consistent support across email clients - something to avoid
*A simpler design is better for Advocacy because of the need for fast turn around
*We could very easily "template" this as Exact Target allows for dropping in content areas easily rather than creating an entire email from scratch
*Buttons are best for mobile users as text links can be hard to tap
*It may also be helpful to have an alt-text styling guide for when images don't render
*Another good design inspiration source: https://www.pinterest.com/marketingcloud/email-swipe-file/
*Ben N. is sharing FireFox & You newsletter code created by DEG with us as it has been road tested.

**Comment by edrushka** [comment]
Making this a P1 for the first week back in Jan.

**Comment by mmmavis** [comment]
I'd like to advocate strongly for single column design + avoid using background images. :bowtie:

**Comment by valianttry** [comment]
Wow the design above for Teach a level up and makes me excited about what's possible!

In the new year let's huddle to look at past emails together. Then, we can also talk about projected needs. I can also offer some best practices for improving response that are tried-and-true that may influence our design choices. I think we may need something versatile, or perhaps a couple of variants for advocacy vs. fundraising for example. :+1:

**Comment by cassiemc** [comment]
Exciting, thanks for the input @valianttry. FYI, I wanted to point you to a ticket we have open for templatizing many of our shared needs – I'll likely be reaching out to you for input around this topic eventually. #https://github.com/MozillaFoundation/plan/issues/644

**Comment by lovegushwa** [comment]
Much of this work is now happening over here:
https://github.com/MozillaFoundation/encryption_campaign/issues/39

We're building 4 templates, but starting with video first since video is crucial to launching beat 1.

**Comment by lovegushwa** [comment]
Now moved to MozillaFoundation/encryption_campaign#39
