### ISSUE TITLE
Add PKR currency support

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#1200]
Got a request from a donor to add PKR currency support. Stripe is capable of processing it.

**Comment by ScottDowne** [comment]
I agree with this being in bluesky because.

There are many many more.

Full list: https://support.stripe.com/questions/which-currencies-does-stripe-support#currencygroup1

We probably don't want a single drop down with a hundred plus items, it would make finding anything in it pretty hard, so we picked a handful we thought would be best.

Not saying we don't add PKR, we just shouldn't be adding one because we can, because we can add lots.

We would need a better UI/UX solution than a single dropdown to handle all of these, which I think might be a next year idea.

**Comment by ScottDowne** [comment]
Closing this in favour of https://github.com/mozilla/donate.mozilla.org/issues/970.
