### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#13]
Then file bugs and setup the testing we want.

**Comment by adamlofting** [comment]
This ticket is about tests we want to write for our JS code.

I will file tickets for monitoring we want to setup for testing the staging and production environments (see #4 )

**Comment by ScottDowne** [comment]
What I really want is something that clicks through the form and makes various test donations. Mainly a stripe donation with the test credit card, and gets as far as opening the paypal page. 

Tests that could run locally, on staging, and right on production would be great.

I'll see if this exists anywhere...

but creating a test for /stripe with the stripe test data and listen for a success message would be fairly easy and is a critical path.

**Comment by ScottDowne** [comment]
I have a test that makes a test donation: https://github.com/mozilla/donate.mozilla.org/pull/86

to run it:
```
npm install
npm test
```

**Comment by adamlofting** [comment]
:smile:

**Comment by ScottDowne** [comment]
Things I want to do before this is 100% (nothing is ever really 100%)

In this order, likely, because it's logical.

- [ ] No jank and very little false positives, this should stay checked, because it's important
- [ ] Selenium test runs in one command, npm run test:selenium
- [ ] Selenium test turns off server after tests are done
- [ ] Framework for running multiple tests
- [ ] Selenium tests display results
- [ ] Readme for adding new tests
- [ ] Some readme instructions on what belongs in a selenium test
- [ ] Travis runs selenium tests
- [ ] All tests run in multiple browsers, right now it's just ff.
- [ ] npm run test also runs selenium tests

**Comment by adamlofting** [comment]
We'll continue on this today if time, then push the remainder to next heartbeat.

This is an ongoing task.

**Comment by ScottDowne** [comment]
@alicoding Giving you this as another P2.

I know you wanted to figure out automated testing of components, so landing a single test as an example how that works would be a good start.

**Comment by alicoding** [comment]
Moving this to next heartbeat. I'm still working on Pontoon and will be working on currency switching stuff.

**Comment by ScottDowne** [comment]
I am pushing for this to be a P2

**Comment by alicoding** [comment]
I think I'm okay closing this ticket now. Now that we have 100% coverage, but I feel like we did most of the component test now, but will file few other tickets to make sure we have few extra selenium tests to run.

**Comment by adamlofting** [comment]
:+1: Great work on this Ali.
