### ISSUE TITLE
Accept bitcoin donations for Thunderbird

### ISSUE THREAD

**Issue by rkent** [mozilla/donate.mozilla.org#1601]
I notice that the Firefox donation page accepts bitcoin, and includes a link for that plus a link for check information on the donate page. Is there any reason we cannot have the same options in Thunderbird?

**Comment by valianttry** [comment]
Accepting bitcoin ended up being incredibly complex, drawn out, and ultimately not very fruitful. It took over a year from deciding we would accept bitcoin to launching the bitcoin donation form. We had to launch a new vendor relationship with Coinbase to accept bitcoin. Coinbase can do instant conversion to USD (a regular bank cannot do this). We also had a lot of back and forth with our tax lawyer about what it means to be a nonprofit that accepts crypto currency, which was also very in depth and complicated.

Despite all of this, and a very vocal community of people who trade in bitcoin demanding we accept bitcoin, our actual revenue from bitcoin is very small. We have raised <$20,000 USD since October 2014 or about 0.5% of our total donation revenue from bitcoin giving. My advice is: It is not worth the pain and trouble.

**Comment by rkent** [comment]
"My advice is: It is not worth the pain and trouble." And since the pain and trouble is mostly put onto MoFo, we are certainly not in any position to push this, so we'll accept your advice for now. In the one day since I wrote my initial request though, I've already had a request for bitcoin, so as you say there is a vocal demand for this.

On a similar issue, my experience with my own payment providers is that many people around the world expect to pay with bank transfers, and I did not see any option for that within the contribution flow. I can attest from experience with Fastspring that bank transfers are also a lot of "pain and trouble" as they go through a single payment consolidator that seems to lose the payments if anything goes wrong, like people not filling out the form exactly as requested. But I do accept it, and the charges are not any higher (to me) then the usual percentage cut from the payment provider.

How do you handle requests for bank transfers? Or is there some option for that that I am missing?

**Comment by rkent** [comment]
I've seen some other ongoing discussions about bank transfers, so I see that is still an open question. Let me then close this issue: we won't push for bitcoin on Thunderbird.

**Comment by valianttry** [comment]
Sorry just saw this @rkent . Bank transfers are possible, they are just extremely expensive for us to receive and process from non-US donors (where most come from). A lot of the discussion is about fees and bank contracts, so the cost and viability varies widely. We definitely want to prioritize making bank transfer easier for donors if possible, it's a P1. I'm not sure what the implications are for Thunderbird.

**Comment by rkent** [comment]
We have no expectation that you will go to special effort for
Thunderbird above and beyond what you are doing for general donations,
so we are happy to let bank transfers be unavailable for Thunderbird,
and reopen the question if you get a viable solution for general
donations working.

**Comment by valianttry** [comment]
sounds good! We will def. let you know.
