### ISSUE TITLE
Missing two strings for l10n

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/donate.mozilla.org#1666]
`How can I get a receipt for U.S. tax preparation purposes?` section on FAQ page.

https://github.com/mozilla/donate.mozilla.org/blob/6b058bd134e92610c8aeedb093f7294e4d9a33d1/src/pages/faq.js#L68

**Comment by yfdyh000** [comment]
Also, `faq_item_4_paragraph_f` are "Not on the current page" on https://pontoon.mozilla.org/.

**Comment by TheoChevalier** [comment]
The first one is hardcoded on purpose (only displayed for en-US), and the second one is just Pontoon not detecting the string, probably because of the trailing space. But it is on the page and properly localized, it can be checked on the staging server in German for instance https://donate.mofostaging.net/de/faq#item_4

Let us know if you see anything else :)

**Comment by yfdyh000** [comment]
Thanks for your answer, everything looks good.
