### ISSUE TITLE
Setup suggested recurring donation amounts based on one-time donation

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate.mozilla.org#1811]
This may be in the original epic ticket, but we should confirm them here

**Comment by WillatMozFdn** [comment]
yes, copied over from the original epic:
General parameters:

    the one-time donation is processed first, so we know we have that transaction processed already

    if someone donates 0-14.99$, we do NOT fire the ask for a monthly.

    if someone donates $15 to $34.99, we suggest $5 monthly

    if someone donates $35-59.99, we suggest $10 monthly

    $60-119.99, suggest $15 monthly

    $120-$250, suggest $20 monthly

    above $250 suggest $30 monthly

Ideally, we would set the monthly to start not immediately, but one month from today. (If that's not possible, we just start the monthly right away.)

**Comment by alanmoo** [comment]
We should also discuss how these amounts convert to reasonable suggestions with different currencies.

**Comment by WillatMozFdn** [comment]
Hey Alan,

Would it help if we restricted this down to 2-3 locales/currencies?  I'm
thinking EN-US ($), DE (euros) and FR (also euros).  Based on some recent
snippet tests, I think this will get us a very high percentage of what we
need ... and hopefully simplify this question, since the amounts for
dollars and euros will be very similar if not the same.

Let me know what you think, thanks!

 - Will

**Comment by alanmoo** [comment]
Sounds reasonable to me. Cc @pomax

**Comment by gideonthomas** [comment]
@WillatMozFdn, to clarify, should we go ahead and just use the exact same amounts for DE (€) and FR (€) as EN-US ($)?

That is to say for EN-US, FR, and DE:

| One-time Donation ($ or €) | Suggested Monthly Donation ($ or €) |
|---|---|
| 0 - 14.99 | - |
| 15 - 34.99 | 5 |
| 35 - 59.99 | 10 |
| 60 - 119.99 | 15 |
| 120 - 250 | 20 |
| above 250 | 30 |

**Comment by WillatMozFdn** [comment]
@gideonthomas ... yes.  Let's just use the exact same amounts in Euros and dollars.

ALSO -- will reply separately in #1835 with more details, but Alan and I have a meeting set up Monday with the guys at Trilogy interactive who set up  https://cstage-zz.trilogyinteractive.com:10444/test-upsell.html?show_amount=true to try and find out how their system works on the back end.  That will go a long way to informing what we are and are not able to to in terms of the flow for the user.  So, more updates on that one Monday.... and thanks to you all for your hard work on this one so far!

**Comment by gideonthomas** [comment]
Thanks @WillatMozFdn! Morphing this into an engineering ticket to setup these amount suggestions in code.

**Comment by gideonthomas** [comment]
@WillatMozFdn were there other currencies we wanted this done for? If so, could you or @TheoChevalier update the conversion amounts for each of those currencies like the table above for $ and €?

**Comment by alanmoo** [comment]
@WillatMozFdn Mentioned UK would be good if it's not too tough, but I don't know about the amounts.

**Comment by ScottDowne** [comment]
I'm doing it in a way where we can add some JSON values to a currencies file to easily enable more currencies for this.

**Comment by ScottDowne** [comment]
Initially we're going with:

USD and EUR

| One-time Donation | Suggested Monthly Donation |
|---|---|
| 0 - 14.99 | - |
| 15 - 34.99 | 5 |
| 35 - 59.99 | 10 |
| 60 - 119.99 | 15 |
| 120 - 250 | 20 |
| above 250 | 30 |

AUD and CAD

| One-time Donation | Suggested Monthly Donation |
|---|---|
| 20 | 6 |
| 45 | 12 |
| 80 | 20 |
| 150 | 25 |
| above 250 | 30 |

GBP

| One-time Donation | Suggested Monthly Donation |
|---|---|
| 10 | 4 |
| 25 | 10 |
| 50 | 15 |
| 100 | 20 |
| above 200 | 30 |

KRW (because why not)

| One-time Donation | Suggested Monthly Donation |
|---|---|
| 16000 | 5500 |
| 40000 | 10000 |
| 67000 | 16000 |
| 135000 | 22000 |
| above 280000 | 33000 |

**Comment by ScottDowne** [comment]
Pretty sure we can close this now.

We have a few initial ranges, we can now iterate on this and add more and more as we localize the string.
