### ISSUE TITLE
[Donate] Re-skin post donate screens

### ISSUE THREAD

**Issue by kristinashu** [mozilla/donate.mozilla.org#2009]
Based on https://github.com/mozilla/foundation.mozilla.org/issues/1534

Design post donate screens:
- Thank you confirmation + email signup
- Share prompt

Current screens: (need to add "no thanks" link in email signup mozilla/donate.mozilla.org#1998)
<img width="234" alt="image" src="https://user-images.githubusercontent.com/1068783/41006867-1f072c0a-68d8-11e8-891d-d9ad3f6542e9.png">

<img width="265" alt="image" src="https://user-images.githubusercontent.com/1068783/41006862-17e2396a-68d8-11e8-8a59-e1f322af15c5.png">

**Comment by kristinashu** [comment]
Here's the first past at this https://redpen.io/p/thbfb2535f83162d2d

**Comment by kristinashu** [comment]
@taisdesouzalessa @ScottDowne can I please get your opinion on these [post donate screens](https://redpen.io/p/thbfb2535f83162d2d)? So the screens are:

#### 1. New donate page

![red-pen-961ca2ea-bc01-4620-fdea-3197b97c4df8](https://user-images.githubusercontent.com/1068783/41881024-269a69f0-7896-11e8-86da-d80be3bb5e0f.jpg)

#### 2. After credit card payment users see this email signup screen. 
This model style is pulled from the post petition signing https://github.com/mozilla/foundation.mozilla.org/issues/1589#issuecomment-399239182. Does this feel ok?
![red-pen-93651d83-51d3-42a1-e86d-2a700aa03b41](https://user-images.githubusercontent.com/1068783/41881025-26b4a4a0-7896-11e8-9105-c0367b4577e2.jpg)

#### 3 (option A). If the signup or dismiss the signup screen then they see this share screen.
This behavior is similar to post petition flow where the form is replaced by the share buttons.
![red-pen-6fe0fc31-9ade-42f0-9cf7-a918e17b4a54](https://user-images.githubusercontent.com/1068783/41881022-266b8dec-7896-11e8-9a59-f9ff78940a79.jpg)

#### 3 (option B). Alternatively, we could instead show anther modal.
Dismissing this modal would show the donate form again.
![red-pen-49a94822-14de-49ab-b023-2aff204a1206](https://user-images.githubusercontent.com/1068783/41881023-26820766-7896-11e8-90d4-c03f086b354e.jpg)

**Comment by taisdesouzalessa** [comment]
@kristinashu those look nice!! I know the copy come from the old version but as a user I would like to know what the email I'll receive will be about. I miss some context encouraging users to give their email address.

In 1 (New Donate Page), if a user click on the blue button (credit card option), will they still see the old screen? Our logo is outdated there.
<img width="369" alt="image" src="https://user-images.githubusercontent.com/22157921/41930715-b9406184-7930-11e8-92e1-b5c0e4c3a029.png">

In 2 (after credit card payment), what happens after users hit "Sign Up"? Do they receive a feedback the email went through?

I prefer 3 (option A) instead a pop up after a pop up (option B). The only thing I would recommend is to have the title be "Tell your friends" (like option B) because in the previous screen we already said "From all of us at Mozilla, thank you" and it seem redundant to see it in this screen again.

**Comment by kristinashu** [comment]
Good points @taisdesouzalessa, thanks!

- Here's the Credit Card screen with updated logo.
![donate x-large copy 12 2x](https://user-images.githubusercontent.com/1068783/41988347-a612d284-79f0-11e8-96e2-d36cade66428.jpg)

- If people come from email then I don't think we will be showing the newsletter prompt, so I think we should keep some sort of thank you message on the share screen. Rather over thank than under!

- @ScottDowne what happens right now if someone signs up to the email? Is there a confirmation?
<img width="235" alt="image" src="https://user-images.githubusercontent.com/1068783/41988276-6f7cbb68-79f0-11e8-92e8-e18a8d051248.png">

Here's a WIP implementation ticket https://github.com/mozilla/donate.mozilla.org/issues/2022

**Comment by TheoChevalier** [comment]
> If people come from email then I don't think we will be showing the newsletter prompt, so I think we should keep some sort of thank you message on the share screen. Rather over thank than under!

+1, the newsletter prompt is also not displayed for all languages, only for the ones where people can subscribe
