### ISSUE TITLE
Generating New Page

### ISSUE THREAD

**Issue by ryanleesipes** [mozilla/donate.mozilla.org#2034]
Ryan here, with Thunderbird. I've been poking around this project a little bit. Looking at generating a new page almost identical to the normal donation page, but with some messaging thanking the user for downloading Thunderbird. The idea is that once a person clicks download on the Thunderbird website and the download begins, they will be redirected to a donation page.

I say all that to ask, what do I need to do to create a new page with proper routing? Please assist.

**Comment by TheoChevalier** [comment]
Hi Ryan,

Instead of creating a completely separate page, would setting up a basic copy test work for your use case?

- Redirect users to something like https://donate.mozilla.org/thunderbird/?test=download-ty
- Add some conditionals in https://github.com/mozilla/donate.mozilla.org/blob/master/src/pages/thunderbird/about.js#L18 to display different strings when the page gets loaded with this test parameter.

If yes, I can find previous examples of tests we did.

**Comment by TheoChevalier** [comment]
Ok, cool! Just found this, I think it’s very similar to what you want: https://github.com/mozilla/donate.mozilla.org/pull/1847/files This PR was adding several alternative strings to the main description on the homepage

`this.props.test` reads the value of the test parameter, so that it’s easy to do some conditionals around that.

**Comment by ryanleesipes** [comment]
I've created a pull request for this: https://github.com/mozilla/donate.mozilla.org/pull/2039

**Comment by TheoChevalier** [comment]
Fixed! Thanks Ryan

**Comment by TheoChevalier** [comment]
Should be up in a few minutes on staging https://donate.mofostaging.net/thunderbird/?test=tbdownload

**Comment by ryanleesipes** [comment]
@TheoChevalier looks great! When will we see it go live?

**Comment by TheoChevalier** [comment]
@ryanleesipes As soon as we will have enough localization coverage for the strings I’ve exposed in addition to this one, or sooner in case there’s a security vulnerability that requires a push to production

**Comment by ryanleesipes** [comment]
@TheoChevalier is there any place to track the localization coverage?

**Comment by TheoChevalier** [comment]
@ryanleesipes Here’s the general overview https://pontoon.mozilla.org/projects/fundraising/ but I’m not sure that would be useful to you, I’m mostly waiting for specific strings in specific locales.

**Comment by TheoChevalier** [comment]
Hi Ryan, 

It looks like the strings I’m monitoring are pretty far in the queue, and I’m ok-ish to release them in English for now, so I’ve hit the deploy button.

This is now live here: https://donate.mozilla.org/thunderbird/?test=tbdownload

**Comment by ryanleesipes** [comment]
Thanks @TheoChevalier could you ping me when the rest go live?

**Comment by TheoChevalier** [comment]
Hey @ryanleesipes, everything merged on master went live, so I’m not sure what you meant by the rest. Were you thinking about specific translations?

**Comment by ryanleesipes** [comment]
@TheoChevalier yeah, well, generally we're looking at a redirect for anyone who downloads over to the site. Germany and Japan are our top two, but we have downloads from pretty much everywhere. Right now we are implementing the redirect for English, but I wanted to track when other regions were localized for so we can implement the redirect for those regions too.

**Comment by TheoChevalier** [comment]
Sounds good, you can keep track of languages ready in the `LOCALES` tab: https://pontoon.mozilla.org/en-GB/fundraising/all-resources/?search=%22Thank+you+for+downloading%22&string=189238

I will do regular deploys
