### ISSUE TITLE
Support WeChat as a Payment Type

### ISSUE THREAD

**Issue by ryanleesipes** [mozilla/donate.mozilla.org#2118]
Every Email I get from a Chinese user requests that we add the ability to make donating possible via WeChat. I wanted to see if this had ever been considered.

I imagine we could get away with only showing this to people who view the donation page in the Chinese language to avoid confusion for other users.

Ideas? Concerns? Is this a reasonable idea?

**Comment by ryanleesipes** [comment]
@jessevondoom sorry to ping you, just wanted to draw someone's attention to the issue and see if this is out of scope or a reasonable issue to raise?

**Comment by WillatMozFdn** [comment]
@ryanleesipes unfortunately this is very low on our priorities list at the moment.  We do not currently have Chinese language localization capabilities on the MoFo side, or content about MoFo in Chinese ... very few email subscribers in China (mainland or otherwise) ... and very few donors there.  New payment systems are a very significant lift for us requiring developer time and integration with accounting systems.

**Comment by ryanleesipes** [comment]
@WillatMozFdn No problem, just wanted to see if this was a possibility. Thanks for the response!
