### ISSUE TITLE
Localization Issue on Russian Thunderbird Page

### ISSUE THREAD

**Issue by ryanleesipes** [mozilla/donate.mozilla.org#2123]
The word: оставанется needs to be changed to останется on the Russian translation of the Thunderbird donate page.

How can I go about getting this changed?

Screenshot of the wrong word:
![russian-donate-word](https://user-images.githubusercontent.com/2141621/49103551-dfb3e800-f238-11e8-8ba3-1cfd186423e6.png)

**Comment by TheoChevalier** [comment]
Hi Ryan, I’ve added a suggestion here, https://pontoon.mozilla.org/ru/fundraising/messages.properties/?search=%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%B0%D0%BD%D0%B5%D1%82%D1%81%D1%8F&string=149462

Russian localizers will take it from there and review the suggestion, closing this issue here.

Thanks for passing along the feedback!
