### ISSUE TITLE
Some non-US Addresses Rejected

### ISSUE THREAD

**Issue by ryanleesipes** [mozilla/donate.mozilla.org#2133]
I have raised the issue of certain zip codes being rejected in the past. I'm sure this is related, but I have seen a few Emails come in from users that claim that their donation was rejected because of their address.

What is happening here? Is there a way to fix it? What criteria must an address meet in order for it to be accepted?

**Comment by WillatMozFdn** [comment]
we recently made some changes on the back end in Stripe to review instead of just rejecting these donations.  It's a lot more work on our end, but seems to be worth it, income improvements in the low four figures.  Closing for now, Ryan, please let us know if you hear of other instances of this happening.  Thanks!
