### ISSUE TITLE
Revive PayPal Transaction DB Service

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#223]

**Comment by jbuck** [comment]
I have the database with data from 2013-01-01 now running on Postgres 9.4. I'm currently running the transaction download app to get an up-to-date list of transactions. Next step would be running this app somewhere that is not my laptop :)

**Comment by jbuck** [comment]
@adamlofting This is up to date as of now, but since it's running on my laptop you won't get any transactions overnight. I'll work on getting this running in AWS tomorrow. I've emailed you the details of the instance.

**Comment by jbuck** [comment]
I got it working with convox after much discovery and enlightenment. It turns out:

- Getting database access working across VPC's is a huge PITA. I ended up just allowing the current EC2 instance ip's access to the database
- It's really important to have your web service running on the correct port
