### ISSUE TITLE
Scope user survey

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#292]
As we build out our funnel, let's see where and how a user survey fits in. I'm proposing we scope in the following way, but feel free to hack:

1. Decide what we want to know e.g why do people donate? why do they support Mozilla? are our donations asks annoying (a la wikimedia's survey) etc.
2. Write the questions.
3. Figure out where the best part in the funnel is. Share screen? Thank you email?
4. Implement for Germany if time permits (the issue will be L10N). Otherwise EOY.

@valianttry @rebsd can you take a crack at question #1? 
cc @lovegushwa

**Comment by valianttry** [comment]
@adamlofting  says we can use the standard "thank you" confirmation page to push a survey to a random segment, or alternately, we can use a survey vendor secured by MoCo. This can be ready in time for Germany fundraising campaign.

Other thoughts on survey strategy:

* After speaking to Watsi.org and Wikimedia, they are able to get deeper more meaningful input from telephone surveys or focus grouping, which they augment with online survey data. Right now we are not resourced to do high-touch surveys like that, so we should gather some data with a low lift short donor survey after they make a donation.

Possible simple, open-ended question:
We would love to know why you decided to donate -- tell us! [comment box]

**Comment by edrushka** [comment]
ohhhh! I love the open-ended comment box idea! That could actually help us shape the questions for a future survey!

**Comment by adamlofting** [comment]
#### Clarification

> @adamlofting says we can use the standard "thank you" confirmation page to push a survey to a random segment, or alternately, we can use a survey vendor secured by MoCo. 

On any thank you page (e.g. by locale), we can add a survey to a random segment using the already approved [SurveyGizmo](http://www.surveygizmo.com/) account. 

#### Question

* What's our capacity to make use of feedback written in German? 

#### Just a note

> After speaking to Watsi.org and Wikimedia, they are able to get deeper more meaningful input from telephone surveys or focus grouping, which they augment with online survey data. 

* We'd have to start asking people for phone numbers if we want to do this. One option is to add a field to the survey saying something like... *If you'd be happy for us to talk more about this please add your phone number*. Noting also, we'd probably need to restrict this to EN audiences.

**Comment by valianttry** [comment]
@adamlofting Watsi uses a very high-touch strategy. They email individual donors 1:1 and thank them for giving, then ask if they'd be willing to talk by phone and give feedback. Small response group, but high value. 

I think we could translate German feedback. It's taken in as text and we could easily (I think) drop it into a spreadsheet and recruit L10N to take it on as a project.

**Comment by edrushka** [comment]
Agree we should limit scope of asking for phone numbers for high-touch follow up to EN audiences to start.

**Comment by valianttry** [comment]
Hey there! I just had a great meeting with Gregg Lind and Matt Grimes in User Advocacy and they had some really awesome ideas for how we can implement a user survey using SurveyGizmo as @adamlofting suggested.

The meeting notes are here:
https://docs.google.com/document/d/1RDGpBW9s10keaSqfb6nLfhDg6LaSuc_ZI5jZQvdSJ5Y/edit

Implementing a survey is easy, we need to write the survey and indicate where in the user flow we want it to show up. After our discussion, and a chat with @bniolet1 I propose we use the survey to assess one of our most basic hypotheses: Most Firefox user/donors give because they believe they are "paying for software" vs. "supporting a mission."  Right now, we don't know the answer to this Q and it's a basic one. We think it's a good place to start.

We will do this in US EN only for simplicity's sake.

Effort seems really minimal -- Gregg and Matt will help with setup if we can propose copy / what we want to ask + where we would like it to be in the user flow.

**Comment by edrushka** [comment]
Ok. I can file a copywriting ticket. Who should I assign it to? And do Gregg and Matt have a delivery date in mind?

**Comment by valianttry** [comment]
Hey @edrushka  -- You can assign copy writing to me -- i already have a head start :)

Implementation date is up to us, let's say December 10ish milestone. That gets us good traffic but also gives us a little time to finalize copy. We only need to flip this on for a while, the survey doesn't have to be shown to every donor.

**Comment by edrushka** [comment]
I'm going to close this since the discussion has moved to #746.
