### ISSUE TITLE
Investigate and decide on a plan for IE8

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#336]
- [x] See how broken IE8 is with our current build - and estimate effort to make it work using our existing tech stack - we expect this to be too difficult and slow down the rest of our development.
- [x] If the effort is too high, let's ship a simple fall back such as browser detection for IE routes users to our static HTML back-up form.

**Comment by alicoding** [comment]
Blocked by https://github.com/mozilla/donate.mozilla.org/issues/345

**Comment by ScottDowne** [comment]
Investigate the amount of work here is a P1. Adding a simple solution if this is complex is a P1.

Actually going in and fixing everything is a P2.

**Comment by alicoding** [comment]
I've spent so much time to get React router version 1.0 beta to work properly for both client and server and it doesn't seem to be straightforward or easy to setup at all since it is still a beta version and their docs still not that good to follow. We might need to wait for their 1.0 stable release to get IE8 fixes at least.

**Comment by adamlofting** [comment]
Thanks for looking into that so thoroughly @alicoding 

I agree we shouldn't spend more time on getting React working with older IE right now, so I've filed a new bug to do the simpler browser sniffing and redirect.
