### ISSUE TITLE
Update preset form values

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#392]
Follow up task from #381 

Form values:
https://docs.google.com/spreadsheets/d/14RsrZZ9V9Tx3jvYoYT5fYQYW1hETJkCRVVGxR7U65TU/edit?usp=sharing

Existing currency presets:
https://github.com/ScottDowne/donate.mozilla.org/blob/currency-drop/data/currencies.js#L12

We also need to add the option to vary the one-off vs monthly arrays.

**Comment by ScottDowne** [comment]
So, having frequency update presets was harder than I thought.

This is because the query string is the source of truth for the presets, frequency on the other hand was source of truth on the form.

This is the opposite of what we need. Presets need to be controlled by frequency, but we attempt to define it before frequency exists. We can uplift frequency to the query string too, but now we end up with query string state that is also form state. Makes submitting a headache.

The issue is due to complexity of trying to keep the query string in sync with state. I say make the query string a one time thing, and state changes in the form just update the form. This isn't because I don't like the url staying in synch with the state, I just find it to be a headache.

Maybe later after we have some tests we can tackle the concept of one source of truth on the query string, but for now, not worth it.

**Comment by adamlofting** [comment]
:+1: Agreed. State changes in the form only need to update the form (especially in the P1 category).

**Comment by ScottDowne** [comment]
https://github.com/mozilla/donate.mozilla.org/pull/416
