### ISSUE TITLE
Implement transaction fallback in donation form

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#393]
Follow on from #302 

We have a collection of simple HTML pages that don't require server side functionality to process transactions.

These are in the existing repo, and have the url slug `paypayl-donate`:

* e.g. https://donate.mofostaging.net/en-US/paypal-donate/

As part of our build/deploy process, we want to publish a duplicate copy of the static HTML and assets needed for these pages to S3. 

These pages will be our emergency forms in case of an outage for our primary forms on Heroku.

**Comment by jbuck** [comment]
Instead of a building a separate form and deploying it elsewhere we should take the fallback logic built into the form and put it into our main form. We could do client-side detection of "Can I contact the donate.m.o server and successfully do a transaction?" and if that fails then we fall back to "send token directly to SQS for Stripe" and "use old Paypal donation flow for Paypal".

**Comment by ScottDowne** [comment]
What does it look like to send data to SQS? Is it straight forward?

**Comment by ScottDowne** [comment]
@cadecairos thoughts on this?
