### ISSUE TITLE
Plan for failure

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#4]
Todo in this ticket:
- List known points of failure from last years campaign
- List potential points of failure in new architecture
- Estimate cost of downtime for these
- Estimate cost of automatic failover systems
- Build testing plan (e.g. load testing new system)
- Decide on monitoring requirements

**Comment by adamlofting** [comment]
cc @jbuck

**Comment by jbuck** [comment]
Exported from the etherpad:

================================
Things that can go wrong (engineering)
================================

Deployment / Build services
 * Travis CI
   * Runs tests
     * Manual testing in lieu of running it on Travis CI?
   * Run deployments
     * If deployment script is within repository, could a human run the deployment script?
     * Before campaign starts, document how to run manual deploy and ensure several engineers have permissions to run the deployment
 * Github down
   * Stores code
     * Could mirror code to repositories elsewhere (AWS CodeCommit has private git repos)
       * If this is quick and easy to do, this is good. 
   * Stores issues
     * Gmail archives everything
     * Bugzilla as a back-up?
     * For short term outage, we can communicate in real-time
   * Stores documentation???
     * If documentation is in Github wiki, that's stored in a git repo that could be mirrored
     * Documentation could be stored elsewhere; would need to plan for that
   * 

Hosting Services
 * Heroku? or whatever we end up hosting on
   * Can't push new versions of code
     * Is it a critical fix, or can it wait 30 mins?
     * Can we fail-over to an alternate provider (another Heroku region, another provider alltogether?)
       * Do we need to be able to manage this at the DNS level or CDN level?
         * Figure this out.
       * Action: make sure enough staff know how to make these changes if needed (documentation and training)
   * Heroku not responding to requests (Heroku is down)
   * Monitoring options
     * Pingdom (basic uptime is easy, also provides transaction monitoring where you specify a list of steps to do)
     * Test response times for API
     * HTTP errors (5xx are key)
     * Newrelic APM
   * Load Testing (our code on Heroku)
     * Research if Heroku gives info about dyno usage (cpu, memory)
     * Decide how we scale (and if we can automate this)
     * Make sure enough staff know how to
       * Reboot heroku
       * Scale up the number of dynos
     * Over-engineer for German campaign, then review the data to plan for EOY
   * Enable prebooting https://devcenter.heroku.com/articles/preboot
   * Slow loading for first user
     * Only applies if running free single dyno instance
       * Mitigate by running multiple dynos
 * AWS down
   * SQS (Message queue)
     * Have a list of multiple queues we can use (including direct browser POST)
     * And we can have queues in multiple regions too
     * We should use SQS as much as possible
   * Cloudfront (CDN)
     * A different CDN provider perhaps? Need to see if it's worth it
   * EC2 (running application code)
     * Heroku as a back-up? Running in different regions?
   * Route53 (DNS)
     * A different DNS provider perhaps?
   * S3 (static html)
     * This never fails
   * For all AWS, documentation and training for enough staff to change things we thing might need to change at short notice.

Essential services we rely on in real-time (if these go down, we can't process donations)
 * Stripe down
   * Disable Stripe payments
   * Can we queue Stripe payments somehow?
 * Paypal down
   * Disable PayPal
   * Turn on Stripe and/or Coinbase
   * Display our mailing address so people can send cheques lololol
 * Coinbase down
   * Disable Coinbase payments
   * Can we display a static Bitcoin address that people could send donations to?

Non-essential (in terms of transactions) services running on page
 * Optimizely
   * Make sure page loads correctly if Optimizely is down, or responding slowly
     * Can we automate this test somehow?
       * Yeah, maybe modify hosts file and see what happens, or run dummy servers to simulate badly behaving servers
 * Google Analytics
   * Make sure page loads correctly if GA is down, or responding slowly
     * Can we automate this test somehow?
 * Exact Targét for Email Subscriptions (+ Basket noted below)
   * If either ET or Basker or down, can we queue the subscription without breaking the UX?
     * Yes, this should be an easy win (put it in SQS)
 * Exact Targét for Email Broadcast
   * Low risk unless down for so long we can't send a key email.
     * BSD as backup

Our own code
 * Page load too slow
   * optimize our page load using Google PageSpeed/YSlow
   * Are there any other page optimization tools
 * We ship bad code to production
   * lots of testing + critical code reviews / FIRE THE PERSON WHO PUSH BAD CODE!
     * Write a test that ensures we don't push the same bad code to production
 * form error because we didn't test all of them?
   * writing unit tests
 * old BSD weirdness that we might have missed to remove?
   * God I hope we've removed everything
 * React weirdness that we don't know about or haven't test? (e.g. routing, state in React)
 * browser doesn't support something we're using
   * quantify what browsers we're supporting, test using all of them!
 * We translated something wrong and it's being broadcast to millions of Mozillians (ie snippet)
   * Translations in source code, not stored in a separate system
 * language detection didn't work as expected. DE is supported but we still serve EN
   * tests tests tests
 * CDN configuration is wrong
   * never let jbuck "let me make one little tweak" store configuration in git repo, only make changes via that
 * We write a bad Optimizely test that breaks the donation flow
   * Have transaction monitoring constantly running on staging/production
 * The network is unreliable
   * Retry requests where it's safe to retry
 * XSS, clickjacking attack
   * Use http header security configured properly to stop most/all of these

MoCo Code / Services
 * Baket for Email Subscriptions
 * Mozilla L10N
 * DNS for donate.mozilla.org

External Risks
 * DDOS attack
   * snippet lol
 * Too much fraud and a payment provider blacklists us

Who else in our engineering team, or our broader Mozilla colleagues should we ask to review this plan?
 * 
 * 
 * 
 * 
 * 


https://github.com/mozilla/donate.mozilla.org/issues/4

**Comment by adamlofting** [comment]
I've turned all the recommendations from this document into individual tickets in this repo.

**Comment by adamlofting** [comment]
Closing this, as all the granular tasks have been files.
