### ISSUE TITLE
Localize FAQs

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#437]
We link to https://wiki.mozilla.org/Donate which is in all English in the German form.

I don't really think this is super great. Are we aware and OK with this? Do we have options?

**Comment by alicoding** [comment]
I guess the bigger question here would be can we make/translate it in different languages? Is there any legal related stuff, USA only content?

**Comment by jbuck** [comment]
I think we should add the FAQ to donate.mozilla.org so that we can translate it. Thoughts?

**Comment by alicoding** [comment]
@jbuck I remember a discussion with @edrushka and @valianttry about adding a FAQ, but can't remember exactly why this is not going to happen for German's campaign, but we were thinking of adding it for sure.

**Comment by jbuck** [comment]
@alicoding doesn't mean we still shouldn't do it!

**Comment by alicoding** [comment]
@jbuck no, I totally agree on doing it, but I just can't remember why we agreed on not doing it on this campaign.

**Comment by valianttry** [comment]
@jbuck  and @alicoding The reason we did not P1 this is because it is localized to EN US audience right now, and it has a lot of legal / policy language that would need to be reviewed, vetted for a DE audience, and edits made (some of which might need legal review and approval). Also much of the content relates to BSD UI -- so that would also need to be reviewed, updated. In short, this is agreed NOT ideal for DE, but we would need content review and editing which would take lots of time even before localization.
