### ISSUE TITLE
How much of the address do we need to ask for

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#462]
For fraud reasons, how much of a user's address do we need?

Can we get away with just asking for zip and card cvc?

From discussion #449

**Comment by valianttry** [comment]
@ScottDowne the answer to this Q may be different for Kount vs. Stripe's built-in fraud protection. 

A separate Q is usefulness of this data for email address optin -- We may request postal code and/or country so that we can do geo-targeting for advocacy and fundraising email in the future. cc @adamlofting to get his opinion on whether we should ask for country and/or zip for email record keeping -- or if he has any experience from WWF on this.

**Comment by adamlofting** [comment]
> @adamlofting to get his opinion on whether we should ask for country and/or zip for email record keeping -- or if he has any experience from WWF on this.

Sorry, I nearly missed this ticket! 

WWF's approach was very different to Mozilla, and also managed on a country by country office basis. E.g. in the UK, we were only interested in donations linked to full addresses as the ROI calculations were based on lifetime engagement rather than one-off transactions (and we would be spending money on the media to put the message in front of potential donors). Also, advocacy was closely tied to a supporters political constituency, so postcode was critical.

It all depends on our strategy.
