### ISSUE TITLE
Verify that API secrets are only used in one place

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#477]
Action from #82

**Comment by ScottDowne** [comment]
I can take this one if you have not started.

**Comment by jbuck** [comment]
Go for it

**Comment by ScottDowne** [comment]
This is secure, for now...

All of our public envs need to go through webpack in a fairly explicit way before the client can use it. We only do this for the envs we know the client needs, and not just because it's public.

We don't pass around secret keys, we just wait until we need them then use them once.

Maybe we can make it more mistake proof, but I'm not sure how yet.

What I'm thinking is something that uses joi to limit what we can send to the client via webpack.

**Comment by adamlofting** [comment]
Shall we close this now?

**Comment by ScottDowne** [comment]
Yeah, I wanted to but wanted to give others a chance to add any more ideas for things we can do.

I feel like that's happened, so closing.
