### ISSUE TITLE
Need giving amount spread in preparation for renegotiating PayPal fees

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#483]
@jbuck I need some information to use as ammo for negotiating with PayPal. I'm hoping you can help (also ccing @adamlofting in case Adam already has this data at hand)

I want to see if they'll give us better terms for "micropayments" of below $10, since those are most of our donors.

I need the spread of donation amounts; e.g. how many people gave <$3? How many gave $4 - $5? How many gave $10? I need the data sort of in format like this:
![who_gave_mozilla__200_000____mozilla__view_source_fundraising](https://cloud.githubusercontent.com/assets/9830371/10236745/6b74136e-685e-11e5-9831-25fe1fdae33a.png)

**Comment by valianttry** [comment]
reference: https://github.com/MozillaFoundation/2015-fundraising/issues/41

**Comment by adamlofting** [comment]
Here are 2014 Transactions for PayPal

![transactions2014](https://cloud.githubusercontent.com/assets/1901816/10247361/7b6383a6-6910-11e5-85bd-abf7de4b6e27.jpg)

It's worth noting that those buckets are 'up to and including' the max value. E.g. the row 5-10 includes all $10 gifts. In fact, most of that bucket is $10 gifts because of the default button values:

<img width="807" alt="screenshot 2015-10-02 14 21 55" src="https://cloud.githubusercontent.com/assets/1901816/10247426/f00b5d6e-6910-11e5-8570-5c283e5b84e7.png">
