### ISSUE TITLE
Qs about the BSD Google Analytics report at start of the DE campaign

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#499]
Hi @adamlofting  I'm looking at the report here and have a few Qs about what I'm seeing:
https://www.google.com/analytics/web/?hl=en#dashboard/Pvut_X9rREKMSQK2M9Mgqg/a35433268w64184110p65898710/%3F_u.date00%3D20151004%26_u.date01%3D20151006/

-- Under "source / medium" why is such a large % of revenue listed under bing / referral? Seems the largest % of revenue should be "desktop-snippet" based on the # of transactions
-- What does PayPal+ Donation and BSD+Contribution mean? (My guess was monthly gifts)
-- conversion rates for bing / organic and paypal.com = 100%+ -- is there a huge fraudulent donation in there?

I realize all this might be moot if we're able to switch to Stripe soon! Also as an aside, I was going to label this "metrics" but noticed that label isn't in here -- is this the wrong repo for metrics Qs? Let me know!
![fundraising__bsd_pages__-_google_analytics](https://cloud.githubusercontent.com/assets/9830371/10315738/dcd01f0c-6c10-11e5-8752-3d6b23280335.png)

**Comment by adamlofting** [comment]
There were several 'major gifts' in GA in recent days where the donor was referred via Bing, but you'll have to validate if those are legit donations in BSD/PayPal. This was before the DE campaign started and seems unrelated to the snippet launch.

I think the `PayPal+Donation` is just and issue with parsing the string on our old forms' conversion tracking - I would treat those as a typo. We didn't have good metrics on recurring gifts on the old system (we do on the new system).

Bing/organic level of transactions is extremely low. I suspect the 120% is just because someone donated twice in a single session. 

Lastly, this repo is fine for metrics - just tag me in the ticket and I'll see it. :+1:
