### ISSUE TITLE
Confirm if donation arrays are correct per locale

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#518]
right now our initial amounts might not be great for all currencies.

we can insert any values here for defaults unique to currencies.

**Comment by adamlofting** [comment]
The current initial amounts are based on researching the typical fundraising asks by a couple global NGOs (Mostly WWF and Unicef depending on who was active in each locale).

https://docs.google.com/spreadsheets/d/14RsrZZ9V9Tx3jvYoYT5fYQYW1hETJkCRVVGxR7U65TU/edit#gid=0

But if we want to tweak any of these to reflect differing expectations for Mozilla, let's track that in this ticket.

This is the latest version of the data being used on the site:
https://github.com/mozilla/donate.mozilla.org/blob/master/data/currencies.js

I think this question is for @valianttry so assigning the ticket.

**Comment by adamlofting** [comment]
We can also set the one-off and monthly amounts to be the same here if we don't want the array to change as user's choose between monthly and one off. See discussion in #672

**Comment by valianttry** [comment]
@adamlofting @ScottDowne I did some work on this -- I created a spreadsheet for defaults starting with the cost of a loaf of bread (based on some research online):
https://docs.google.com/spreadsheets/d/14ZWYtGF2xC459SXUT-otxGXzlM5peLp-HqFgPSjf2eM/edit#gid=0&vpid=A1

I think these amounts work as defaults for both one-time and monthly gifts for the snippet traffic. What do you think?

**Comment by valianttry** [comment]
@adamlofting looking at the spreadsheet you shared earlier that includes WWF / UNICEF numbers -- our average gift is so much lower for the majority of our donors. I started with a "slightly higher than a loaf of bread" amount based on our average... but would like to hear your thoughts on this.

**Comment by adamlofting** [comment]
Nice. 

* The comparison to the cost of bread is a good indicator
* We should make sure that the lowest amount per currency shouldn't end up being less than our lowest accepted amount in USD - I think minimums per currency are already specified in the code
* Round numbers make more sense to me, and feel more localised rather than we're presenting a US ask converted into that currency - I think all the local fundraising asked I looked at were round numbers
* We should work from our average gift, but in the long run remember that this is largely determined by who we've asked to donate and how much we prompted them for in the past.
 * Especially when we move to year round appeals to warmer channels we can get more advanced about this - e.g. DE mozilla.org vs DE snippet
 * Culture of giving varies by locale and history of all NGO fundraising there. Ireland for example had almost 10x the average gift of the UK for some fundraising campaigns I've seen in the past.

**Comment by ScottDowne** [comment]
@valianttry This looks ready for dev. Should I start?

**Comment by ScottDowne** [comment]
I agree with @adamlofting we should make sure they are rounded numbers.

Also we're going to need to define varients for one time and monthly, and a single min amount.

**Comment by valianttry** [comment]
hi @ScottDowne so here is my attempt:

https://docs.google.com/spreadsheets/d/14ZWYtGF2xC459SXUT-otxGXzlM5peLp-HqFgPSjf2eM/edit#gid=1351196652&vpid=A1

* I am not sure if there are different minimum amounts for specific currencies. I built this using a minimum conversion of $2 USD. Please double check this, because they will get an error if the minimum is actually higher than the lowest amount in the defaults.
* I adjusted defaults down for currencies with a particularly weak show against USD. 
* The default amount changes based on selection of monthly or one-time. 
* In most cases I made the smallest amount the default for monthly giving. We don't have enough data to know our monthly gift average for most currencies, so this is an educated guess.

@adamlofting we are adding higher presets for mozilla.org donate URLs. But we def. want to get much more scientific and locale-specific. There is a SLEW of tests we could do -- e.g. default monthly amounts that are slightly higher than the minimums here.... oh the possibilities!

**Comment by ScottDowne** [comment]
@valianttry If I read this right, the raw table is for when people come here not from the snippet, and not from mozilla.org?

Also, the min amounts, and some of the presets are not nice round numbers, which might be a little weird.

In general this table is kinda confusing.

**Comment by valianttry** [comment]
hi @ScottDowne 

Ignore the tab labeled "raw" that's just where i dumped a bunch of data.

So the 2 tabs that matter: "Snippet defaults" can just be our "defaults" but the same ones we'll use for snippet. The "mozillaORG" tab is for ... mozilla.org or where we anticipate a higher average gift.
All the numbers in the 2 tabs that matter should be nice round numbers. I also deleted some columns that aren't important in those tabs that should help clarify things.

Let me know if you need anything more -- i'm getting ready to go eat dinner so won't be looking at Github for the rest of the evening probably.

**Comment by ScottDowne** [comment]
@valianttry What about monthly presets being different than one time presets?

**Comment by ScottDowne** [comment]
@valianttry Also did you get anywhere on min amount values per currency?

**Comment by jbuck** [comment]
That's easy for Stripe:
https://support.stripe.com/questions/what-is-the-minimum-amount-i-can-charge-with-stripe

**Comment by ScottDowne** [comment]
The only place we cannot override presets is organic google searches, so part of me wants our flat defaults to be ideal for those average amounts.

Another part of me wants the defaults to make sense for the spot where we get the most traffic, which would actually be snippet.

**Comment by valianttry** [comment]
@ScottDowne we might want to revisit all of these decisions next year. For now I've assumed:
-- Presets for default search = presets for snippet (this is not ideal since our search avg gift is high compared to snippet avg gift). It's find for now. We don't get that much search traffic.
-- We should talk to @adamlofting about whether we should set any defaults at all -- Wikipedia doesn't default to any amount on any form that I've seen, and their average gift is considerably higher than ours. Maybe we should stop suggesting a default amount? Would be a good test.
-- I calculated the minimum amounts in the gift arrays based on the equivalent $2 USD conversion, and it looks like that will work OK based on the link ^ @jbuck just shared. We make very little revenue in countries where the value of the local currency is significantly lower than the USD so I'm not too worried about turning off those donors for now.
-- Preset amount arrays are the same in my spreadsheet for both Monthly or One-Time (I thought this might simplify things greatly, but maybe I'm wrong?). If we want to show the "monthly" selected version to users; e.g. during a test to push monthly donations -- then the default selection is the lower amount.

**Comment by ScottDowne** [comment]
@valianttry K, that cleared it up, and I pushed up a good start, but ended up a bit behind today so we'll put it onto production tomorrow and can do another pass if we want.

**Comment by adamlofting** [comment]
> -- We should talk to @adamlofting about whether we should set any default amount at all 

I agree on this as a future test. My previous data is for a different audience/ask/flow.
