### ISSUE TITLE
Option to signup on form if paypal

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#618]
Not sure if this is a good idea... It might reduce conversion rate.

However, I wanted to get people's thoughts.

How I see this happening is after you click PayPal, instead of redirecting immediately... we display a "donate now" button, and a "sign up now" checkbox.

At the point, we still need email and privacy *only* for the signup. We don't want to present them with this until after they click signup, we slide down and display the email input and privacy checkbox.

Thoughts? Signups vs conversion rate. Testable?

**Comment by adamlofting** [comment]
I think I see what you mean. 

In the *PayPal scenario*, we don't ask the user for any personal details before redirecting them to Paypal:

<img width="719" alt="screenshot 2015-10-26 10 33 25" src="https://cloud.githubusercontent.com/assets/1901816/10726804/0e97b088-7bcd-11e5-8470-43fb02783391.png">

But the place we're thinking of adding the email opt-in is for the *Credit Card* flow:

<img width="671" alt="screenshot 2015-10-26 10 34 55" src="https://cloud.githubusercontent.com/assets/1901816/10726816/2ce4fec4-7bcd-11e5-8650-7f929fb20f44.png">

--

I also think that adding an extra email opt-in option in that otherwise very smooth PayPal flow risks damaging conversion rate. 

We could always test it, but I think our energy and effort would be better invested in optimizing the email sign-up form on the thank you page for PayPal donors.

**Comment by ScottDowne** [comment]
Works for me.

I'm just going to close this.
