### ISSUE TITLE
Stripe requires less personal information than bsd did and what does that mean for us

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#632]
The core of this idea is we collect the donation on step 2 as soon as we can, and step 3 is an optional, info collection step which also serves as a thank-you page.

Stripe, as a minimum, requires, cardnumber, and expiry date (MM/YY).

CVC is helpful for fraud, the rest isn't needed at all... for a donation.

![steps](https://cloud.githubusercontent.com/assets/197334/10768539/135a89c4-7cb8-11e5-8a8a-970e156763c7.jpg)

**Comment by edrushka** [comment]
I love this ticket because it raises some very interesting questions about what personal info we *can* collect (according to our privacy policy, the Basket api, hacky mofo solutions etc.) and what we *should* collect. I definitely feel like testing and establishing the **minimum** user data threshold is valuable. It'll be so interesting to see if minimal data = more donations. But from a donor stewardship perspective, I want ALL THE INFO! Mailing address, city, postal code etc. I'm sure there's a happy medium, but it will be fun to test the extremes.

**Comment by jbuck** [comment]
@edrushka it's worth considering that the amount of data we get from PayPal donations is more limited compared to credit card donations. Here's what we capture for each PayPal donation:

* transaction id
* timestamp
* email
* name
* amount
* currency
* country

**Comment by ScottDowne** [comment]
At this point all that's lift might be running a test?

**Comment by adamlofting** [comment]
> At this point all that's lift might be running a test?

@ScottDowne do you know if this is configured in the Stripe admin interface for all transactions, or could we spin up a copy of the one-page form with different checkout requirements?

If the latter, it would be great to test this with Optimizely and know the impact for sure.

**Comment by ScottDowne** [comment]
@adamlofting We can configure it in the one page.

**Comment by ScottDowne** [comment]
This is covered in other tickets now.
