### ISSUE TITLE
When switching between monthly/one-off maintain array selection position, rather than amount

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#672]
![untitled_presentation_-_google_slides](https://cloud.githubusercontent.com/assets/9830371/10952159/2d5b8f6e-82f6-11e5-84f1-3a0be607fa53.png)

**Comment by ScottDowne** [comment]
@adamlofting 

Hm, I think I agree, it's a bit weird.

The purpose of this is so we ask for less from monthly subscriptions.

However, we have the amount buttons before the frequency anyway, so it's kinda counter productive to switch it after they have made a choice.

It's still useful if it's set to monthly as a default config, but in that case, we don't need it to update as the user makes changes.

@adamlofting any thoughts?

**Comment by adamlofting** [comment]
Yes, this was deliberate, but can be changed if we prefer. This is pretty common practice for monthly/one-off online giving and something I did a lot of testing around at WWF. The typical ask was £3 per month, but for a one-off gift this would be £40 instead.

If we want to use the same amounts for monthly and one-off, I suggest we set them to the same values for now rather than remove this functionality, as that gives us the option to test in the future.

I'm going to close this ticket, because the work to resolve this either way will be addressed in #518 but I'll P1 that corresponding ticket so it doesn't get missed.

**Comment by ScottDowne** [comment]
@adamlofting This would be less of an issue if we asked for frequency before amount. I wonder if that would be a better experience in general?

**Comment by adamlofting** [comment]
Looking at some examples for comparison today there is one thing these do differently:

* http://www.oxfam.org.uk/donate
* https://support.wwf.org.uk/
* http://www.unicef.org.uk/donate/donate-now/

If you select the 3rd option in an array, and then switch between monthly and one-off, you get the 3rd option in each array. This gives you a new donation amount (which is the objective), rather than moving your selection within the array. 

I think this is a better UX as it makes the intention of chaning the array clearer, so I suggest we do that.

**Comment by ScottDowne** [comment]
@adamlofting I agree the objective should now be to give you a new donation amount. Although I'm not seeing these links maintain the position. They all seem to revert to amount amount, which may or may not keep position. If that happens to move the position, it'll move the position.

Other things I noticed in those links that might be interesting and helpful for us.
- http://www.oxfam.org.uk/donate
  - No selected state, instead directly takes you to the next step.
  - single/monthly selector above amounts.
- https://support.wwf.org.uk/
  - has a default preselect amount for monthly and single
  - remembers your monthly and single select but independently of each other. So toggle monthly/single toggles two remembered states.
  - Can change/shuffle the position.
  - uses radio buttons which visually have less impact when they change
- http://www.unicef.org.uk/donate/donate-now/
  - has monthly/single above donation amount
  - can change the position
  - has a default preselect amount for monthly and single
  - remembers your position for monthly and single independently
  - I kinda like this one the most

I think we should get @lovegushwa 's thoughts. However, my vision is something like this.
1. Move monthly/single selector above amounts. This might be good in general even without considering jarring visuals while shifting.
2. Changing the monthly/single selector changes the amount selected, doesn't retain it. Maintain the selected position if there is one. If other is selected, keep the amount.

**Comment by ScottDowne** [comment]
This should be on staging in a moment.

@adamlofting can you give it a spin tomorrow?
