### ISSUE TITLE
Changing my mind and switching to Credit Card after I just selected PayPal sends me to PP anyway

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#676]
https://donate.mofoprod.net/en-US/?test=new-flow-test

If I click "PayPal" then change my mind and click "Credit Card" i'm redirected to PayPal anyway.

Seems like if I make that quick switch it should overide the redirect to PP?

**Comment by adamlofting** [comment]
Marking this as related to #415 because if we immediately display the paypal loading message, this will be less confusing. 

However it raises a new question, should we allow a cancel/exit icon while the paypal loading message is displayed? This would give people the option to change their mind and switch to credit card, but might unintentionally be clicked by people who are intending to donate via Paypal.

**Comment by ScottDowne** [comment]
I'm not sure how I feel about a cancel button.

I want to experiment with making the button a link.

**Comment by valianttry** [comment]
I don't think we need 'cancel'. People can always just hit "back" once PP loads, and we're talking about a smallish # of people.

**Comment by ScottDowne** [comment]
After taking a quick look, canceling it is probably not worth it, when compared to having a spinner.

We agreed to close this for now.
