### ISSUE TITLE
Step 2 is not linked if you go back to Step 1

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#678]
If i select amount (Step 1) and then go to Step 2, I should be able to go back by clicking the circle (1) . If I review my amount selected, I should then also be able to click the circle (2) if i want to return to Step 2. Instead, (2) is not a link, so I therefore can only click the red "NEXT" button to get to (2)

![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/10953464/094c4ca6-82fd-11e5-8da1-b909b272114b.png)

**Comment by KasperChristensen** [comment]
Haven't worked with React before, so having a little problem finding where this happens.
But insted of just checking for class complete for making a menu point active, my idea was:

Check if current div.page-breadcrumb is empty, it not empty make current index + 1 clickable.

**Comment by ScottDowne** [comment]
Hey @KasperChristensen and welcome :)

I haven't really thought about this one too much, just enough to know it's a little tricky.

You're on the right path. Somehow we need to check if the current navigation page is valid or not, which is what you're trying to do by checking div.page-breadcrumb. Then make the next clickable or not.

However, I pictured clicking on the navigation buttons when things are not valid, would trigger error messages that could be fixed by the user.

I think the easiest way would be to copy functionality out of the next button, which has a list of props to validate, and can be quite robust, example: `<NextButton validate={["cardNumber", "expMonth", "expYear", "cvc"]}/>` https://github.com/mozilla/donate.mozilla.org/blob/master/components/next-button.jsx

If something like that lived on the navigation buttons, adding functionality similar to the next button might be straight forward.

This would mean currentIndex + 1 is always clickable, and clicking that would either move to that page, or display errors.

Thoughts? You're welcome to work on this bug.

**Comment by ScottDowne** [comment]
@KasperChristensen Just a quick check in, to see if I can answer any questions you might have or help in any way :)

**Comment by KasperChristensen** [comment]
This seems to work.

I would have liked to add the amount validation to step 3 aswell insted of:
```javascript
Number(this.props.activePage)+1 >= Number(this.props.index)
```
But i couldnt get that to work a the same time with ["cardNumber", "cvc", "expMonth", "expYear"]. And since ["cardNumber", "cvc", "expMonth", "expYear"] is not on the first page the validation fails and you could go directly to step 3.

**Comment by ScottDowne** [comment]
@KasperChristensen Looking good, so far I only see one small suggestion, and I think some updates have landed since you started because it looks like you're reverting some recent changes. So I think you need to rebase, but that shouldn't change much of your code. Most of the conflicts are in  pages/sequential.jsx but also some around the DisplayNavigationButton component.

**Comment by ScottDowne** [comment]
@KasperChristensen I really appreciate your patch.

Unfortunately, I forgot, but we were running a test between two donation forms: https://donate.mofostaging.net/en-US/one-page/ and https://donate.mofostaging.net/en-US/ to see which produces more donations.

This morning the test finished, and they ended up being just as good, but the one page is much simpler in complexity and allows us to close a few more bugs, including this one.

This bug is actually one of those bugs that the complexity of the sequential page created.

We're going to switch the default page to one-page, which really lowers the priority of finishing this bug, and I wanted to tell you before you worked on it further :(

**Comment by ScottDowne** [comment]
I'm still going to keep the sequential form in the repo, but it won't be the default form.

Still willing to merge your patch, it's just not a priority.

**Comment by ScottDowne** [comment]
For context: https://github.com/mozilla/donate.mozilla.org/issues/953
