### ISSUE TITLE
Double check Google Analytics for the new Stripe form are working correctly

### ISSUE THREAD

**Issue by valianttry** [mozilla/donate.mozilla.org#742]
Hey @adamlofting ! The form is GO and we're seeing donations coming in.

I've been watching the Stripe Dashboard, as well as your Google Analytics report here:
https://www.google.com/analytics/web/?authuser=0#dashboard/x2x17FAsShuixRj2bK-YpQ/a49796218w101806119p105783219/%3F_u.date00%3D20151110%26_u.date01%3D20151111/

I noticed a discrepancy in the totals, $267 in GA and $594 in Stripe. Since GA is presumably counting both PayPal and Stripe transactions, that seems like the inverse of what we would expect to see. Or is there lag time for the GA report? Or perhaps the timezones are different?

![fundraising__mofo_hosted_pages__-_google_analytics](https://cloud.githubusercontent.com/assets/9830371/11110391/fdc95a32-88af-11e5-896e-e18cede99476.png)

![dashboard](https://cloud.githubusercontent.com/assets/9830371/11110393/08bbd3c0-88b0-11e5-8c02-0765e8a07709.png)

**Comment by adamlofting** [comment]
There is definately something amiss here. I've just compared Weds for GA and Stripe as that should be a complete day of GA data.

But... GA isn't reporting any Paypal donations yet, and is underreporting Stripe by a long way. 

Let me investigate, as this was good in staging when it was written, but the site has evolved since the earlier QA.

**Comment by adamlofting** [comment]
I've done some debugging and think I've identified the issue. I've asked the devs to decide on the best solution between three options in #750 and hopefully this fix can ship asap.

**Comment by jbuck** [comment]
@adamlofting We've landed a patch, could you verify that everything is working on your end?

**Comment by adamlofting** [comment]
This is looking good. We're now seeing the PayPal transactions, and it looks like more Stripe transactions. On Monday I'll do a more thorough comparison of Stripe records to GA using the data over the weekend.

<img width="1168" alt="screenshot 2015-11-13 14 42 09" src="https://cloud.githubusercontent.com/assets/1901816/11148474/dc956e1c-8a14-11e5-89c8-565e252f2aec.png">
<img width="1169" alt="screenshot 2015-11-13 14 42 21" src="https://cloud.githubusercontent.com/assets/1901816/11148475/dc9b2e9c-8a14-11e5-974b-108b55772203.png">

**Comment by adamlofting** [comment]
Also @valianttry a good thing to be aware of is that the monthly donation amount is now multiplied by x 12 in our GA and Optimizely reporting so that in our A/B testing, if one variant drives more monthly donors we make our decisions based on the long term value. I.e. we value $3/month more than $10 one-off.

This will help us optimize for total income in a way that we couldn't do last year.

**Comment by valianttry** [comment]
@adamlofting this is really great. I'll make sure people who are reporting our #s internally and externally only use the Add-on total (not the total from GA, which would be inflated with the multiplication factor).

**Comment by jbuck** [comment]
@adamlofting I think this is working, but would love a confirmation from you :)

And if it is working, could you close this ticket? Thanks!

**Comment by adamlofting** [comment]
Just crossed checked the data over the weekend, and this is looking good now. GA does report less than the actual totals in Stripe, but that is to be expected given tracking protections options etc.
