### ISSUE TITLE
Check the target URL in new test snippet for DE

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#785]
@valianttry I think we might have an error in the URL, or we forgot to add the GA tracking params to the new snippet we're testing: `5465`. It's working fine from a user point of view, but we're not attributing the conversions to the snippet so we can't compare old form to new form precisely yet.

Who should I talk to to check this?

**Comment by jbuck** [comment]
@jbertsch maybe?

**Comment by valianttry** [comment]
Check with @ScottDowne first. We had a weird error when we launched and had to pause while he and Jean Collings sorted out some utm stuff.... so it might have gotten broken in that fix?

**Comment by ScottDowne** [comment]
@adamlofting yes, this is a bug, and because snippets can take so long to land, it's been slow to fix.

We did remember to add the tracking in the url, but I wasn't aware that's how we did that, because I was up to that point working with "donate.mofostaging.net/" <- notice the no params there. So my code would add "?amount=selectedAmount&presets=etc" which worked in staging and with all my tests data.

Once it hit prod, these tracking values went in and we had a broken snippet. I just didn't know we added params when the snippets got on prod.

The solution was to fix it in the snippet code (which is time consuming) and also temporarily remove the tracking from the url so we can at least start getting 5% to test the new form and stripe a bit (which has found things too, so that's good).

I *thought* we were tracking snippets via the querystring "snippet_name" based on looking at the code.

So if there is a temporary way to track this via that query_string? New snippet has "snippet_name=5465" and old has "snippet_name=5464". If that doesn't work, we'll need to wait until Monday, likely, before this is shipped.

**Comment by adamlofting** [comment]
Thanks @ScottDowne. There's a tonne of value in getting this onto prod as quickly as we did. :+1: 

I dug out the snippets service for reference here: https://snippets.mozilla.com/show/5465/

> So if there is a temporary way to track this via that query_string?

We can identify inbound traffic using `snippet_name` parameter to track number of clicks, but we need the GA params to assign the `source/medium` values for tracking the duration of the session. Currently GA sees the traffic as `direct` because there is no referring URL, and then as `Paypal` after those donors go out to paypal and come back to the site.

Is the `donate.mozilla.org/de/` part of the URL hardcoded? I thought in some snippets this was a variable that could be edited in the snippet admin, but that might just be the standard snippet.

These are the params we need to add:

* `&ref=EOYFR2015&utm_campaign=EOY2015&utm_source=desktop-snippet&utm_medium=snippet&utm_term=5465`

(keeping the existing functional parameters in place too)
* `&amount=.......&frequency=.......&currency=eur&snippet_name=5465`

**Comment by ScottDowne** [comment]
The URL is not hard coded, it's a config. As soon as you add query strings to that config, things break. We ended up with a url like donate.mozilla.org/de/?ref=EOYFR2015&utm_campaign=EOY2015&utm_source=desktop-snippet&utm_medium=snippet&utm_term=5465?amount=.......&frequency=.......&currency=eur&snippet_name=5465

Notice the two question marks? That's the bug. Needs to be fixed in the snippet itself.

**Comment by adamlofting** [comment]
Ah, I gotcha. That makes sense.

**Comment by jbuck** [comment]
@ScottDowne Fixed this
