### ISSUE TITLE
We should default country to the likely one given currency selected

### ISSUE THREAD

**Issue by simonwex** [mozilla/donate.mozilla.org#907]
![image](https://cloud.githubusercontent.com/assets/25260/11320532/e42fd338-904f-11e5-9daf-8a94b20d7647.png)

**Comment by ScottDowne** [comment]
It picked US because you were in en-US, if you go to https://donate.mozilla.org/en-CA/ it does set canada for the country.

I know, not super helpful, because nothing actually links to en-CA...

The current implementation is mostly for more specific locales, en-CA is a bit of an oddity because most Canadians are used to en-US anyway.

**Comment by ScottDowne** [comment]
We're moving to one page form, which does it's own country detection.
