### ISSUE TITLE
Consider using Google AdWords to optimize our SEO

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#957]
Just had a quick conversation with Growth and Analytics expert from MoCo here at the kitchen in Toronto and I captured few great ideas from him regarding ways to get more donors through other channels.

1. Blog post with specific keywords
  A lot of people know Mozilla as a creator of the great browser **Firefox**, but many people who care deeply about the web and net neutrality for some of them don't know that Mozilla plays a big part of this cause. I'm sure that many people want to help and support the cause. 

  We need to blog about things that we've done to focus on the keywords, but also mention ways for people to help donate within the blog post itself. Blog post is a really good way to bring organic search traffic if we do it right.

2. Google AdWords to find keywords to optimize or get people to donate for causes.
  By using Google AdWords will not only help expose our result for keywords that we're trying to optimize, but we can also learn what other keywords people are trying to search when looking for ways to donate to **charity** and **the web**.

I think the amount of work that we'll put for doing the above both task is less and could potentially bring us more traffic to do our test and get more donors from different audience.

@valianttry @edrushka @adamlofting thoughts?

**Comment by adamlofting** [comment]
There are some good ideas in here, but I think we should think about SEO as part of our year round fundraising strategy and not a P1 for the end of year campaign. 

This will be most effective in the context of the MoFo blogging platform @HPaulJohnson is currently thinking about. That platform is likely to have much more content relating to topics like Net Neutrality and our advocacy work, and will see more organic traffic than our donation page is going to. 

Rather than thinking about how we *add SEO to our donation pages*, we could instead think about how we add appropriate donation asks to existing pages that already get more organic 'SEO' traffic.

**Comment by adamlofting** [comment]
I've updated our old Adwords ads in our grant account to point to the new /about/ page, and added a couple of new text variants based on the messages that have been running in the snippet.

<img width="364" alt="screenshot 2015-12-03 15 02 38" src="https://cloud.githubusercontent.com/assets/1901816/11564076/0a0d924c-99cf-11e5-9c81-98974ceeaeb5.png">

**Comment by alicoding** [comment]
♪┏(・o･)┛♪┗ ( ･o･) ┓♪ ┗ (･o･ ) ┓♪

**Comment by valianttry** [comment]
Sometimes I wish Github had a like button. We'll just have to settle for this:
:clap: :+1: :santa:

**Comment by valianttry** [comment]
@adamlofting can we see the ad performance in Google Analytics?

**Comment by adamlofting** [comment]
Yes, once these ads are approved and delivering traffic they should show up in GA as a new 'source / medium'
